### ISSUE TITLE
Match pages fail to load offline

### ISSUE THREAD

**Issue by brendanburkhart** [Pigmice2733/peregrine-frontend#1224]
If you go to a match page (e.g.  online, go offline, and return to/reload the match page, it will be stuck on the loading page. @calebeby thinks this is due to the analysis page. I can't currently fully repro this on dev - the match info and score panels still load, but on the latest deploy preview nothing loads whatsoever besides the loading indicator.

**Comment by varCepheid** [comment]
I don't notice an issue. On this computer and on my phone, when I went offline, the cache brought back the entire page quickly.

**Comment by brendanburkhart** [comment]
I can still reproduce this issue - if you aren't able to reproduce a bug yourself, please ask for help before closing the issue.

**Comment by varCepheid** [comment]
Apologies. Can you send a video or screenshot on Slack so I can try to figure out what's wrong?

**Comment by brendanburkhart** [comment]
To see bug: load a match page (e.g. https://dev.peregrinefrc.com/events/2019orwil/matches/qm2), then either use devtools to go offline or turn off WiFi, and then do a hard reload of the page (ctrl+f5 or similar).

This is a screenshot I just grabbed of what it looks like 
![image](https://user-images.githubusercontent.com/19364314/150444446-89a52734-5857-40df-9381-bbac03c48307.png)

**Comment by varCepheid** [comment]
I don't understand the process of uploading data from a cache or the network well enough to try to deal with this. There seem to be a lot of parts and finding the issue could take a while. If you can try to explain it to me, that would be great.

**Comment by calebeby** [comment]
@varCepheid Yeah this is a tricky one and will likely take at least a few hours to fix. There are several options of how to tackle this, let me know which one would make the most sense:

- I can start to look into this and split this into several smaller issues with more specific details of the individual parts that need to be fixed, with links to the code that corresponds to them and steps to fix. And then you can take on the individual parts one-by-one
- We can tackle this issue together, we could do a Live Share in VS Code and work through it
- If you're not interested in this issue I can do it myself if you prefer
- We can hold off fixing this for a little while until you are more comfortable with working on Peregrine. (I don't like this option as much since this issue is preventing us from merging the new match page + reports stuff to main)
